version: '3.8'

services:
  lmstudio:
    image: ghcr.io/lmstudio-ai/lmstudio:latest
    container_name: lmstudio
    ports:
      - "1234:1234"
    volumes:
      - ./models:/app/models
    command: >
      lmstudio serve --model /app/models/mistral.gguf --port 1234

  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  agents_app:
    build: .
    container_name: lmstudio-agents
    ports:
      - "8501:8501"
    depends_on:
      - lmstudio
      - postgres
      - redis
    environment:
      OPENAI_API_KEY: lm-studio
      OPENAI_API_BASE: http://lmstudio:1234/v1
      OPENAI_MODEL_NAME: mistral
      DATABASE_URL: postgresql://dev:secret@postgres:5432/devdb
      REDIS_URL: redis://redis:6379/0

volumes:
  pgdata: